SetRelationshipBetweenGroups(2, GetHashKey("AGGRESSIVE_INVESTIGATE"), GetHashKey('PLAYER'))
SetRelationshipBetweenGroups(2, GetHashKey("AMBIENT_GANG_BALLAS"), GetHashKey('PLAYER'))
SetRelationshipBetweenGroups(2, GetHashKey("AMBIENT_GANG_CULT"), GetHashKey('PLAYER'))
SetRelationshipBetweenGroups(2, GetHashKey("AMBIENT_GANG_FAMILY"), GetHashKey('PLAYER'))
SetRelationshipBetweenGroups(2, GetHashKey("AMBIENT_GANG_LOST"), GetHashKey('PLAYER'))
SetRelationshipBetweenGroups(2, GetHashKey("AMBIENT_GANG_MARABUNTE"), GetHashKey('PLAYER'))
SetRelationshipBetweenGroups(2, GetHashKey("AMBIENT_GANG_MEXICAN"), GetHashKey('PLAYER'))
SetRelationshipBetweenGroups(2, GetHashKey("AMBIENT_GANG_SALVA"), GetHashKey('PLAYER'))
SetRelationshipBetweenGroups(2, GetHashKey("AMBIENT_GANG_WEICHENG"), GetHashKey('PLAYER'))
SetRelationshipBetweenGroups(2, GetHashKey("AMBIENT_GANG_HILLBILLY"), GetHashKey('PLAYER'))
SetRelationshipBetweenGroups(2, GetHashKey("CIVMALE"), GetHashKey('PLAYER'))
SetRelationshipBetweenGroups(2, GetHashKey("CIVFEMALE"), GetHashKey('PLAYER'))
SetRelationshipBetweenGroups(2, GetHashKey("COP"), GetHashKey('PLAYER'))
SetRelationshipBetweenGroups(2, GetHashKey("SECURITY_GUARD"), GetHashKey('PLAYER'))
SetRelationshipBetweenGroups(2, GetHashKey("PRIVATE_SECURITY"), GetHashKey('PLAYER'))
SetRelationshipBetweenGroups(2, GetHashKey("PRISONER"), GetHashKey('PLAYER'))
SetRelationshipBetweenGroups(2, GetHashKey("FIREMAN"), GetHashKey('PLAYER'))
SetRelationshipBetweenGroups(2, GetHashKey("GANG_1"), GetHashKey('PLAYER'))
SetRelationshipBetweenGroups(2, GetHashKey("GANG_2"), GetHashKey('PLAYER'))
SetRelationshipBetweenGroups(2, GetHashKey("GANG_9"), GetHashKey('PLAYER'))
SetRelationshipBetweenGroups(2, GetHashKey("GANG_10"), GetHashKey('PLAYER'))
SetRelationshipBetweenGroups(2, GetHashKey("HATES_PLAYER"), GetHashKey('PLAYER'))
SetRelationshipBetweenGroups(2, GetHashKey("HEN"), GetHashKey('PLAYER'))
SetRelationshipBetweenGroups(2, GetHashKey("GUARD_DOG"), GetHashKey('PLAYER'))
SetRelationshipBetweenGroups(2, GetHashKey("DOMESTIC_ANIMAL"), GetHashKey('PLAYER'))




