function AddTextEntry(key, value)
	Citizen.InvokeNative(GetHashKey("ADD_TEXT_ENTRY"), key, value)
end
Citizen.CreateThread(function()
    AddTextEntry('so1', '2011 Crown Victoria Police Interspecter')
    AddTextEntry('so2', '2011 Crown Victoria Police')
    AddTextEntry('so3', '2013 Chevy Caprice Police')
    AddTextEntry('so4', '2016 Ford Pursuit Interceptor Police')
    AddTextEntry('so5', '2018 Dodge Charger Police')
    AddTextEntry('so6', '2018 Ford F-150 Police')
    AddTextEntry('so7', '2018 Chevy Suburban Police')
    AddTextEntry('so8', '2018 Chevy Tahoe Police')
    AddTextEntry('so9', '2018 Ford Taurus Police')
    AddTextEntry('so10', '2016 Tesla Model S Police')
	AddTextEntry('so11', '2013 Ford Pursuit Interceptor Police')

    AddTextEntry('hp1', '2011 Crown Victoria Police Interspecter')
    AddTextEntry('hp2', '2011 Crown Victoria Police')
    AddTextEntry('hp3', '2013 Chevy Caprice Police')
    AddTextEntry('hp4', '2014 Dodge Charger Police')
    AddTextEntry('hp5', '2016 Ford Pursuit Interceptor Police')
    AddTextEntry('hp6', '2018 Dodge Charger Police')
    AddTextEntry('hp7', '2018 Ford F-150 Police')
    AddTextEntry('hp8', '2018 Chevy Suburban Police')
    AddTextEntry('hp9', '2018 Chevy Tahoe Police')
    AddTextEntry('hp10', '2018 Ford Taurus Police')
    AddTextEntry('hp11', '2016 Tesla Model S Police')

    AddTextEntry('pd1', '2011 Crown Victoria Police Interspecter')
    AddTextEntry('pd2', '2011 Crown Victoria Police')
    AddTextEntry('pd3', '2013 Chevy Caprice Police')
    AddTextEntry('pd4', '2014 Dodge Charger Police')
    AddTextEntry('pd5', '2016 Ford Pursuit Interceptor Police')
    AddTextEntry('pd6', '2018 Dodge Charger Police')
    AddTextEntry('pd7', '2018 Ford F-150 Police')
    AddTextEntry('pd8', '2018 Chevy Suburban Police')
    AddTextEntry('pd9', '2018 Chevy Tahoe Police')
    AddTextEntry('pd10', '2018 Ford Taurus Police')
    AddTextEntry('pd11', '2016 Tesla Model S Police')

    AddTextEntry('s1', '2011 Crown Victoria Police Interspecter')
    AddTextEntry('s2', '2011 Crown Victoria Police')
    AddTextEntry('s3', '2013 Chevy Caprice Police')
    AddTextEntry('s4', '2014 Dodge Charger Police')

	
	AddTextEntry('viperleo', '2017 Dodge Viper Police')
	AddTextEntry('amggtrleo', '2018 AMG GTR Police')
	AddTextEntry('911turboleo', '2018 Porsche 911 Turbo Police')

    AddTextEntry('utvtrailer', '2018 John Deere 4x4 Trailer')
    AddTextEntry('gator', '2018 John Deere 4x4')
    AddTextEntry('bcso001', '2018 Ford Explorer Interceptor')
    AddTextEntry('c3cvpi', '2010 Ford Crown Victoria Interceptor')
    AddTextEntry('bcso003', '2011 Ford Crown Victoria Interceptor')
    AddTextEntry('bcsotaurus', '2016 Ford Taurus Interceptor')
    AddTextEntry('BHTahoe', '2018 Chevy Tahoe Interceptor')
    AddTextEntry('BHTahoek9', '2018 Chevy Tahoe Interceptor K9')
    AddTextEntry('c3fpiu', '2018 Ford Explorer Interceptor')
    AddTextEntry('c3ram', '2018 Dodge Ram')
    AddTextEntry('pitbull', '2018 Lenco Pitbull SWAT')
    AddTextEntry('bearcat', '2018 Lenco Bearcat SWAT')
	
end)
