function AddTextEntry(key, value)
	Citizen.InvokeNative(GetHashKey("ADD_TEXT_ENTRY"), key, value)
end
Citizen.CreateThread(function()
    AddTextEntry('so1', '2011 Crown Victoria Police Interspecter')
    AddTextEntry('so2', '2011 Crown Victoria Police')
    AddTextEntry('so3', '2013 Chevy Caprice Police')
    AddTextEntry('so4', '2016 Ford Pursuit Interceptor Police')
    AddTextEntry('so5', '2018 Dodge Charger Police')
    AddTextEntry('so6', '2018 Ford F-150 Police')
    AddTextEntry('so7', '2018 Chevy Suburban Police')
    AddTextEntry('so8', '2018 Chevy Tahoe Police')
    AddTextEntry('so9', '2018 Ford Taurus Police')
    AddTextEntry('so10', '2016 Tesla Model S Police')
	AddTextEntry('so11', '2013 Ford Pursuit Interceptor Police')

    AddTextEntry('hp1', '2011 Crown Victoria Police Interspecter')
    AddTextEntry('hp2', '2011 Crown Victoria Police')
    AddTextEntry('hp3', '2013 Chevy Caprice Police')
    AddTextEntry('hp4', '2014 Dodge Charger Police')
    AddTextEntry('hp5', '2016 Ford Pursuit Interceptor Police')
    AddTextEntry('hp6', '2018 Dodge Charger Police')
    AddTextEntry('hp7', '2018 Ford F-150 Police')
    AddTextEntry('hp8', '2018 Chevy Suburban Police')
    AddTextEntry('hp9', '2018 Chevy Tahoe Police')
    AddTextEntry('hp10', '2018 Ford Taurus Police')
    AddTextEntry('hp11', '2016 Tesla Model S Police')

    AddTextEntry('pd1', '2011 Crown Victoria Police Interspecter')
    AddTextEntry('pd2', '2011 Crown Victoria Police')
    AddTextEntry('pd3', '2013 Chevy Caprice Police')
    AddTextEntry('pd4', '2014 Dodge Charger Police')
    AddTextEntry('pd5', '2016 Ford Pursuit Interceptor Police')
    AddTextEntry('pd6', '2018 Dodge Charger Police')
    AddTextEntry('pd7', '2018 Ford F-150 Police')
    AddTextEntry('pd8', '2018 Chevy Suburban Police')
    AddTextEntry('pd9', '2018 Chevy Tahoe Police')
    AddTextEntry('pd10', '2018 Ford Taurus Police')
    AddTextEntry('pd11', '2016 Tesla Model S Police')

    AddTextEntry('s1', '2011 Crown Victoria Police Interspecter')
    AddTextEntry('s2', '2011 Crown Victoria Police')
    AddTextEntry('s3', '2013 Chevy Caprice Police')
    AddTextEntry('s4', '2014 Dodge Charger Police')
	
end)
